language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sfloresb/docker-react -f Dcokerfile.dev .

script:
  - docker run -e CI=true sfloresb/docker-react npm run test
